### ISSUE TITLE
Unify UX of pull-down menu in UserList and RoleEditorModal

### ISSUE THREAD

**Issue by d-hayashi** [dataware-tools/app-user-manager#74]
## Purpose
Feature request

## Description
ユーザごとの Role を選択するためのプルダウンメニューとデータベースごとの permission を選択するためのプルダウンメニューでUXが異なっているので、どちらかに統一したい

具体的な違いは以下の通り

### Role 選択メニュー
<img width="560" alt="スクリーンショット 2021-06-08 12 25 01" src="https://user-images.githubusercontent.com/24401842/121118325-9e164600-c854-11eb-9c9f-cc5589262e0a.png">
項目選択後にメニュー外の場所をクリックすると `キャンセル` になる

### Permission 選択メニュー
<img width="473" alt="スクリーンショット 2021-06-08 12 24 45" src="https://user-images.githubusercontent.com/24401842/121118306-9191ed80-c854-11eb-854a-09e10c6f4a63.png">
項目選択後にメニュー外の場所をクリックすると `確定` になる

**Comment by WatanabeToshimitsu** [comment]
https://github.com/dataware-tools/dataware-tools/issues/77 へ移行
